web/router.ex
defmodule Engine.Router do
  use Engine.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Engine.Auth, repo: Engine.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", Engine do
    pipe_through :browser # Use the default browser stack
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/terms", InfoController, :terms
    get "/privacy", InfoController, :privacy
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    get "/", DashboardController, :index
  end

  # authed routes
  scope "/", Engine do
    pipe_through [:browser, :authenticate]
    # get "/admin-dashboard", AdminDashboardController, :index
    post "/startpack/:id", StartpackController, :update
    post "/startpack/:id/delete-file", StartpackController, :delete_uploaded_files
    resources "/startpack", StartpackController, except: [:new, :create, :delete]
    # post "/projects/:project_id/offers/:offer_id/send_offer", OfferController, :send_offer
    resources "/projects", ProjectController do
      resources "/custom_fields", CustomFieldController, only: [:create, :delete]
      resources "/documents", DocumentController do
        get "/signees/new", SigneeController, :add
        post "/signees/new", SigneeController, :add_signee
        delete "/signees", SigneeController, :clear_signees
      end
      resources "/signees", SigneeController, only: [:create, :delete]
      post "/offers/:offer_id/send_offer", OfferController, :send_offer
      resources "/offers", OfferController do
        # project_offer_altered_document_path(conn, project, offer)
        # /projects/:project_id/offers/:offer_id/altered_documents/sign

        get "/custom_fields/add", CustomFieldController, :add
        post "/custom_fields/:id/save", CustomFieldController, :save
        post "/custom_fields/:id/revise", CustomFieldController, :revise
        get "/altered_documents/sign", AlteredDocumentController, :sign
      end
      put "/offers/:id/response", OfferController, :response
    end
  end

  # admin authed routes
  scope "/admin", Engine do
    pipe_through [:browser, :authenticate_admin]
    get "/dashboard", AdminDashboardController, :index
    get "/custom-fields", AdminDashboardController, :custom_fields
    get "/users", AdminDashboardController, :users
  end

  # Other scopes may use custom stacks.
  # scope "/api", Engine do
  #   pipe_through :api
  # end
end

web/models/user.ex
defmodule Engine.User do
  use Engine.Web, :model
  alias Comeonin.Bcrypt

  schema "users" do
    field :email, :string
    field :first_name, :string
    field :last_name, :string
    field :password_hash, :string
    field :password, :string, virtual: true
    field :verified, :boolean
    field :terms_accepted, :boolean
    field :admin, :boolean, default: false
    has_many :projects, Engine.Project
    has_many :offers, Engine.Offer
    has_one :startpacks, Engine.Startpack

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :first_name, :last_name, :password, :verified, :admin])
    |> validate_required([:email, :first_name, :last_name])
    |> email_changeset(params)
    |> unique_constraint(:email)
  end

  def new_password_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:password])
    |> validate_required([:password])
    |> validate_confirmation(:password, required: true, message: "Passwords do not match")
    |> validate_password()
    |> put_password_hash()
  end

  def email_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email])
    |> validate_required([:email])
    |> validate_format(:email, ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
  end

  def email_verification_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:verified])
    |> validate_required([:verified])
  end

  def registration_changeset(struct, params \\ %{}) do
    struct
    |> changeset(params)
    |> cast_assoc(:startpacks, required: true)
    |> terms_accepted(params)
    |> validate_password()
    |> put_password_hash()
  end


  defp terms_accepted(changeset, params) do
    message = "You must agree to the terms and conditions"
    changeset
    |> cast(params, [:terms_accepted])
    |> validate_required([:terms_accepted])
    |> validate_inclusion(:terms_accepted, [true], message: message)
  end

  defp validate_password(changeset) do
    changeset
    |> validate_required([:password])
    |> validate_length(:password, min: 6, max: 100)
    |> validate_format(:password, ~r/^(?=.*[A-Z])(?=.*\d)(?=.*(_|[^\w])).+$/)
  end

  defp put_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: given_pass}} ->
        put_change(changeset, :password_hash, Bcrypt.hashpwsalt(given_pass))
      _ ->
        changeset
    end
  end
end

web/controllers/user_controller.ex
defmodule Engine.UserController do
  use Engine.Web, :controller

  plug :authenticate when action in [:index, :show, :edit, :update, :delete]

  alias Engine.{User, LayoutView, RedisCli}

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    case Map.has_key?(conn.query_params, "te") do
      true ->
        target_email_hash = conn.query_params["te"]
        target_email = get_target_email(target_email_hash)
        render(conn, "new.html", layout: {LayoutView, "pre_login.html"}, changeset: changeset, target_email: target_email, target_email_hash: target_email_hash)
      false ->
        render(conn, "new.html", layout: {LayoutView, "pre_login.html"}, changeset: changeset, target_email: nil, target_email_hash: nil)
    end
  end

  def create(conn, %{"user" => %{"email" => email} = user_params}) do
    user_params = Map.put(user_params, "email", String.downcase(email))
    # add startpack to the user
    user_params = Map.merge(%{"startpacks" => %{}}, user_params)
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        Engine.Email.send_verification_email(user)
        |> Engine.Mailer.deliver_later()

        # update offers user_id to all offers for this user
        from(o in Engine.Offer, where: o.target_email == ^user.email)
        |> Repo.update_all(set: [user_id: user.id])

        conn
        |> put_flash(:info, "A verification email has been sent to #{user.email}.
        Click the link in the email to gain full access to engine")
        |> redirect(to: session_path(conn, :new))
      {:error, changeset} ->
        case Map.has_key?(conn.query_params, "te") do
          true ->
            target_email_hash = conn.query_params["te"]
            target_email = get_target_email(target_email_hash)
            render(conn, "new.html", layout: {LayoutView, "pre_login.html"}, changeset: changeset, target_email: target_email, target_email_hash: target_email_hash)
          false ->
            render(conn, "new.html", layout: {LayoutView, "pre_login.html"}, changeset: changeset, target_email: nil, target_email_hash: nil)
        end
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User updated successfully")
        |> redirect(to: startpack_path(conn, :index))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully")
    |> redirect(to: user_path(conn, :index))
  end

  defp get_target_email(target_email_hash) do
    case RedisCli.query(["GET", target_email_hash]) do
      {:ok, nil} -> nil
      {:ok, email} -> email
    end
  end

end

web/views/user_view.ex
defmodule Engine.UserView do
  use Engine.Web, :view
end

web/templates/user/edit.html.eex
<div class=" mt6 center">
  <h1 class="k-indigo top--header absolute fw4 mb0">Edit profile</h1>

  <%= link "Dashboard", to: dashboard_path(@conn, :index), class: "link k-indigo no-underline" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <%= link "Startpack", to: startpack_path(@conn, :index), class: "link k-indigo no-underline ml2" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <div class="ma2 k-light-indigo dib">Edit profile</div>

  <%= form_for @changeset, user_path(@conn, :update, @user), fn f -> %>
  <%= if @changeset.action do %>
  <div class="alert pa4 br2 mb4 white bg-light-red b--red tc mt3">
    Oops, something went wrong! Please check the errors below.
  </div>
  <% end %>
  <%= component "form_divider.html", title: "Names" %>
    <%= component "input.html",
    form: f,
    atom: :first_name,
    placeholder: "Brad"
    %>

    <%= component "input.html",
    form: f,
    atom: :last_name,
    placeholder: "Pitt"
    %>

    <%= component "submit_button.html", title: "Update Details" %>
  <% end %>

  <%= link "Change account password", to: password_path(@conn, :new), class: "k-dark-indigo underline" %>
</div>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<div class="vh-100 w-100 mw7-ns center dt">
  <div class="dtc v-mid">
      <div class="ba b--black-10 br4-ns pa4 bg-white h-auto-ns h-100">
        <div class="tc pt3">
          <img src="/images/engine-logo-front.jpg" class="k-w32"/>
          <h2>Create account</h2>
        </div>
        <div class="">
            <%= form_for @changeset, user_path(@conn, :create, te: @target_email_hash), fn f -> %>
            <%= if @changeset.action do %>
              <div class="alert light-red mt3">
                <p>Oops, something went wrong! Please check the errors below.</p>
              </div>
            <% end %>

            <%= component "input.html",
            form: f,
            atom: :first_name,
            placeholder: ""
            %>

            <%= component "input.html",
            form: f,
            atom: :last_name,
            placeholder: ""
            %>

            <%= component "input.html",
            form: f,
            atom: :email,
            placeholder: "",
            class: "mt5",
            readonly: (@target_email != nil),
            value: @target_email
            %>

            <%= component "input.html",
            form: f,
            atom: :password,
            label: "Password (for Engine)",
            placeholder: "Minimum 6 characters, inc: 1 capital, 1 digit, 1 special",
            type: "password"
            %>

            <%= component "checkbox.html",
            form: f,
            atom: :terms_accepted,
            label: "I have read and accept the ",
            link: "/terms",
            link_name: "terms of use"
            %>

            <%= component "submit_button.html", title: "Create" %>

            <div class="tc">
            <h4 class="mv2">Already have an account?</h4>
            <%= link "Log in", to: session_path(@conn, :new), class: "k-dark-indigo link underline mb2" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

web/templates/user/show.html.eex
<%= link "Edit", to: user_path(@conn, :edit, @user), class: "ma2 k-indigo no-underline" %>

<h2>Show user</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </li>


</ul>