web/router.ex
defmodule Engine.Router do
  use Engine.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Engine.Auth, repo: Engine.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", Engine do
    pipe_through :browser # Use the default browser stack
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/terms", InfoController, :terms
    get "/privacy", InfoController, :privacy
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    get "/", DashboardController, :index
  end

  # authed routes
  scope "/", Engine do
    pipe_through [:browser, :authenticate]
    # get "/admin-dashboard", AdminDashboardController, :index
    post "/startpack/:id", StartpackController, :update
    post "/startpack/:id/delete-file", StartpackController, :delete_uploaded_files
    resources "/startpack", StartpackController, except: [:new, :create, :delete]
    # post "/projects/:project_id/offers/:offer_id/send_offer", OfferController, :send_offer
    resources "/projects", ProjectController do
      resources "/custom_fields", CustomFieldController, only: [:create, :delete]
      resources "/documents", DocumentController do
        get "/signees/new", SigneeController, :add
        post "/signees/new", SigneeController, :add_signee
        delete "/signees", SigneeController, :clear_signees
      end
      resources "/signees", SigneeController, only: [:create, :delete]
      post "/offers/:offer_id/send_offer", OfferController, :send_offer
      resources "/offers", OfferController do
        # project_offer_altered_document_path(conn, project, offer)
        # /projects/:project_id/offers/:offer_id/altered_documents/sign

        get "/custom_fields/add", CustomFieldController, :add
        post "/custom_fields/:id/save", CustomFieldController, :save
        post "/custom_fields/:id/revise", CustomFieldController, :revise
        get "/altered_documents/sign", AlteredDocumentController, :sign
      end
      put "/offers/:id/response", OfferController, :response
    end
  end

  # admin authed routes
  scope "/admin", Engine do
    pipe_through [:browser, :authenticate_admin]
    get "/dashboard", AdminDashboardController, :index
    get "/custom-fields", AdminDashboardController, :custom_fields
    get "/users", AdminDashboardController, :users
  end

  # Other scopes may use custom stacks.
  # scope "/api", Engine do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Engine.LayoutView do
  use Engine.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>e n g i n e</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->

  </head>
  <body class="k-bg-lighter-grey k-indigo mb0">
    <header>
      <nav role="navigation" class="flex k-h6 bb k-bg-dark-indigo relative bn">
          <div class="app-container w-100 h4 mt2 center">
              <a href="/" class="h4 ml0-ns">
                <div class="h3 dt pb3 dib fl mr4">
                  <img src="/images/logo-blue.png" class="w3 pv2 dib dtc" />
                  <p class="dib f3 pl2 fw4 white ma0 dtc v-mid">engine</p>
                </div>
              </a>
              <%= if @current_user do %>
            <div class="white fr k-mt3-5 fw4">
              <%= if @current_user.admin do %>
              <%= link "Admin", to: admin_dashboard_path(@conn, :index), class: "back-button link hover-purple white ml3 mv4 mb0-ns outline-0" %>
              <% end %>
              <%= link "Startpack", to: startpack_path(@conn, :index), class: "back-button link hover-purple white ml4-ns ml3 mv4 mb0-ns outline-0" %>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete", class: "back-button hover-purple link white ml4-ns ml3 mv4 mb0-ns outline-0" %>
            </div>
            <% end %>
          </div>
      </nav>
    </header>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 dark-grey bg-light-green b--dark-green" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 mb4 white bg-light-red b--red" role="alert"><%= get_flash(@conn, :error) %></p>
    <article class="k-mt9 center h-100 bg-white relative-ns pb7-ns pb6 min-vh-100-ns relative">
      <main role="main" class="h-100 bg-white app-container center relative">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </article> <!-- /container -->

    <!-- FOOTER -->
    <footer class="relative k-bg-darker-grey white">
      <div class="w-100 h6-ns h-100 bottom-0 app-container center">
        <div class="mt0 mb4 b--black-20 bt">
          <article class="cf mt0">
            <div class="fl w-100 tl pt4-ns pt2 mb3 mb0-ns">
              <a href="http://www.teamengine.co.uk" target="_blank">
                <div class="h3 dt pb3 dib fl mr4">
                  <img src="/images/footer-logo.svg" class="k-w2-5 pv2 dib dtc" />
                  <p class="dib f4 pl2 fw5 white ma0 dtc v-mid"><span class="k-light-grey fw3">team</span> engine</p>
                </div>
              </a>
              <%
                first_name =
                  case @current_user != nil do
                    true -> @current_user.first_name
                    false -> ""
                  end
                last_name =
                  case @current_user != nil do
                    true -> @current_user.last_name
                    false -> ""
                  end
                email =
                  case @current_user != nil do
                    true -> @current_user.email
                    false -> ""
                  end
              %>
              <div class="k-light-grey dib fr-l fr-m fr-ns k-mt0-1 pt3">
                <a class="f4 dib k-light-grey dim link" href='mailto:info@teamengine.co.uk?subject=e+n+g+i+n+e+-+enquiry+from+<%= first_name <> "+" <> last_name %>&body=Dear+Team+Engine,+%0D%0A%0D%0AINSERT+YOUR+ENQUIRY+%0D%0A%0D%0AYour+contacts:+<%= first_name <> "+" <> last_name <> ",+" <> email %>+%0D%0A%0D%0AWe+will+get+back+to+you+on+the+above,+soon!%0D%0A%0D%0A%0D%0AThanks.%0D%0A%0D%0A(if+you+need+help,+please+click+the+"help"+link+in+the+footer+and+complete+the+form)'>contact</a>
                <div class="k-w1px h1 k-bg-light-grey dib pt1 ml1 mr1"></div>
                <a href="https://engineplans.formstack.com/forms/enginesupport" target="_blank"    title="help" class="f4 dib k-light-grey dim link">help</a>
                <div class="k-w1px h1 k-bg-light-grey dib pt1 ml1 mr1"></div>
                <a href="/terms"  target="_blank"   title="Terms" class="f4 dib k-light-grey dim link">terms</a>
                <div class="k-w1px h1 k-bg-light-grey dib pt1 ml1 mr1"></div>
                <a href="/privacy"  target="_blank" title="Privacy" class="f4 dib k-light-grey dim link">privacy</a>
              </div>
            </div>
          </article>

          </div>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app").App.hamburgerAnimate()</script>
    <script>require("web/static/js/app").App.reverseScientificNotation()</script>
  </body>
</html>

web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>

web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Karma!</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="bg-white karma-indigo">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/pre_login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>e n g i n e</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->
    
  </head>

  <body class="bg-white k-indigo">

      <p class="alert pa4 br2 mb4 alert dark-grey bg-light-green b--dark-green" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert pa4 br2 mb4 white bg-light-red b--red" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main" class="bg-near-white">
        <%= render @view_module, @view_template, assigns %>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>