web/router.ex
defmodule Engine.Router do
  use Engine.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Engine.Auth, repo: Engine.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", Engine do
    pipe_through :browser # Use the default browser stack
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/terms", InfoController, :terms
    get "/privacy", InfoController, :privacy
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    get "/", DashboardController, :index
  end

  # authed routes
  scope "/", Engine do
    pipe_through [:browser, :authenticate]
    # get "/admin-dashboard", AdminDashboardController, :index
    post "/startpack/:id", StartpackController, :update
    post "/startpack/:id/delete-file", StartpackController, :delete_uploaded_files
    resources "/startpack", StartpackController, except: [:new, :create, :delete]
    # post "/projects/:project_id/offers/:offer_id/send_offer", OfferController, :send_offer
    resources "/projects", ProjectController do
      resources "/custom_fields", CustomFieldController, only: [:create, :delete]
      resources "/documents", DocumentController do
        get "/signees/new", SigneeController, :add
        post "/signees/new", SigneeController, :add_signee
        delete "/signees", SigneeController, :clear_signees
      end
      resources "/signees", SigneeController, only: [:create, :delete]
      post "/offers/:offer_id/send_offer", OfferController, :send_offer
      resources "/offers", OfferController do
        # project_offer_altered_document_path(conn, project, offer)
        # /projects/:project_id/offers/:offer_id/altered_documents/sign

        get "/custom_fields/add", CustomFieldController, :add
        post "/custom_fields/:id/save", CustomFieldController, :save
        post "/custom_fields/:id/revise", CustomFieldController, :revise
        get "/altered_documents/sign", AlteredDocumentController, :sign
      end
      put "/offers/:id/response", OfferController, :response
    end
  end

  # admin authed routes
  scope "/admin", Engine do
    pipe_through [:browser, :authenticate_admin]
    get "/dashboard", AdminDashboardController, :index
    get "/custom-fields", AdminDashboardController, :custom_fields
    get "/users", AdminDashboardController, :users
  end

  # Other scopes may use custom stacks.
  # scope "/api", Engine do
  #   pipe_through :api
  # end
end

web/models/project.ex
defmodule Engine.Project do
  use Engine.Web, :model

  schema "projects" do
    field :type, :string
    field :budget, :string
    field :name, :string
    field :codename, :string
    field :description, :string
    field :start_date, Ecto.Date
    field :duration, :float
    field :studio_name, :string
    field :company_name, :string
    field :company_address_1, :string
    field :company_address_2, :string
    field :company_address_city, :string
    field :company_address_postcode, :string
    field :company_address_country, :string
    field :operating_base_address_1, :string
    field :operating_base_address_2, :string
    field :operating_base_address_city, :string
    field :operating_base_address_postcode, :string
    field :operating_base_address_country, :string
    field :operating_base_tel, :string
    field :operating_base_email, :string
    field :locations, :string
    field :holiday_rate, :float
    field :additional_notes, :string
    field :active, :boolean, default: true
    belongs_to :user, Engine.User
    has_many :offers, Engine.Offer
    has_many :documents, Engine.Document
    has_many :signees, Engine.Signee
    has_many :custom_fields, Engine.CustomField

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [
      :type,
      :budget,
      :name,
      :codename,
      :description,
      :start_date,
      :duration,
      :studio_name,
      :company_name,
      :company_address_1,
      :company_address_2,
      :company_address_city,
      :company_address_postcode,
      :company_address_country,
      :operating_base_address_1,
      :operating_base_address_2,
      :operating_base_address_city,
      :operating_base_address_postcode,
      :operating_base_address_country,
      :operating_base_tel,
      :operating_base_email,
      :locations,
      :holiday_rate,
      :additional_notes,
      :active,
      :user_id])
    |> validate_required([
      :type,
      :budget,
      :name,
      :codename,
      :start_date,
      :duration,
      :studio_name,
      :company_name,
      :company_address_1,
      :company_address_city,
      :company_address_postcode,
      :company_address_country,
      :holiday_rate,
      :active,
      :user_id])
    |> validate_format(:operating_base_email, ~r/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
    |> validate_length(:description, max: 300)
    |> validate_length(:additional_notes, max: 300)
    |> validate_dropdowns
  end

  def validate_dropdowns (changeset) do
    changeset
    |> validate_inclusion(:type, ["feature", "television"])
    |> validate_inclusion(:budget, ["low", "mid", "big"])
    |> validate_inclusion(:holiday_rate, [0.1077, 0.1207])
  end


  # queries
  # get projects created by specified user
  # commenting out for now because we aren't hitting the index anymore
  # def users_projects(query, user) do
  #   from p in query,
  #   where: p.user_id == ^user.id
  # end
end

web/controllers/project_controller.ex
defmodule Engine.ProjectController do
  use Engine.Web, :controller

  alias Engine.{Project, Document, Signee, CustomField}


  plug :add_project_to_conn when action in [:show, :edit, :update, :delete]
  plug :block_if_not_project_manager when action in [:show, :edit, :update, :delete]


  # project owner plug
  def add_project_to_conn(conn, _) do
    # if project doesn't exist, it should render a 404
    # else add project to assigns
    project_id = case conn.params do
      %{"project_id" => project_id} -> project_id # if we are in an offers route
      %{"id" => project_id} -> project_id # if we are in a projects route
    end
    conn = assign(conn, :project, Repo.get(Project, project_id))

    case conn.assigns.project do
      nil ->
        conn
        |> put_flash(:error, "Project could not be found")
        |> render(Engine.ErrorView, "404.html")
        |> halt()
      _ ->
        is_pm? = conn.assigns.project.user_id == conn.assigns.current_user.id
        conn = assign(conn, :is_pm?, is_pm?)
        conn
    end
  end

  def block_if_not_project_manager(conn, _) do
    # block if current user is not PM
    case conn.assigns.is_pm? do
      false ->
        conn
        |> put_flash(:error, "You do not have permission to view that project")
        |> redirect(to: dashboard_path(conn, :index))
        |> halt()
      true ->
        conn
    end
  end

  def new(conn, _params) do
    changeset = Project.changeset(%Project{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"project" => project_params}) do
    %{"additional_notes" => notes} = project_params
    single_line_notes = Regex.replace(~r/\r\n/, notes, " ")
    project_params =
      project_params
      |> Map.delete("additional_notes")
      |> Map.put_new("additional_notes", single_line_notes)
    user = conn.assigns.current_user
    changeset =
      user
      |> build_assoc(:projects)
      |> Project.changeset(project_params)
    case Repo.insert(changeset) do
      {:ok, _project} ->
        conn
        |> put_flash(:info, "Project created successfully")
        |> redirect(to: dashboard_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end


  def show(conn, %{"id" => id}) do
    project = Repo.get(Project, id) |> Repo.preload(:documents)
    documents = project.documents |> Repo.preload(:signees)

    forms = Enum.filter(documents, fn document -> document.category == "Form" end)
    deals = Enum.filter(documents, fn document -> document.category == "Deal" end)
    info = Enum.filter(documents, fn document -> document.category == "Info" end)
    signees = Repo.all(project_signees(project))
    document_changeset = Document.changeset(%Document{})
    signee_changeset = Signee.changeset(%Signee{})
    custom_field_changeset = CustomField.changeset(%CustomField{})
    custom_fields = Repo.all(project_custom_fields(project))
    custom_project_fields = Enum.filter(custom_fields, fn field -> field.type == "Project" end)
    custom_offer_fields =
      custom_fields
      |> Enum.filter(fn field -> field.type == "Offer" end)
      |> Enum.filter(fn field -> field.value == nil end)

    render(conn,
    "show.html",
    project: conn.assigns.project,
    document_changeset: document_changeset,
    signee_changeset: signee_changeset,
    custom_field_changeset: custom_field_changeset,
    custom_fields: custom_fields,
    custom_project_fields: custom_project_fields,
    custom_offer_fields: custom_offer_fields,
    forms: forms,
    deals: deals,
    signees: signees,
    info: info)
  end

  def edit(conn, %{"id" => id}) do
    project = Repo.get!(Project, id)
    changeset = Project.changeset(project)
    render(conn, "edit.html", project: project, changeset: changeset)
  end

  def update(conn, %{"id" => id, "project" => project_params}) do
    %{"additional_notes" => notes} = project_params
    single_line_notes = Regex.replace(~r/\r\n/, notes, " ")
    project_params =
      project_params
      |> Map.delete("additional_notes")
      |> Map.put_new("additional_notes", single_line_notes)
    project = Repo.get!(Project, id)
    changeset = Project.changeset(project, project_params)

    case Repo.update(changeset) do
      {:ok, project} ->
        conn
        |> put_flash(:info, "Project updated successfully")
        |> redirect(to: project_path(conn, :show, project))
      {:error, changeset} ->
        render(conn, "edit.html", project: project, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    project = Repo.get!(Project, id)

    Repo.delete!(project)

    conn
    |> put_flash(:info, "Project deleted successfully")
    |> redirect(to: project_path(conn, :index))
  end
end

web/views/project_view.ex
defmodule Engine.ProjectView do
  use Engine.Web, :view
end

web/templates/project/edit.html.eex
<div class=" mt6 center">

  <%= link "Dashboard", to: dashboard_path(@conn, :index), class: "no-underline k-indigo" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <%= link "Project", to: project_offer_path(@conn, :index, @project), class: "ma2 no-underline k-indigo" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <%= link "Project details", to: project_path(@conn, :show, @project), class: "ma2 no-underline k-indigo" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <div class="ma2 k-light-indigo dib">Edit project</div>

  <h1 class="k-indigo top--header absolute fw4 mb0">Edit project</h1>

  <%= render "form.html", changeset: @changeset,
                          action: project_path(@conn, :update, @project),
                          button_text: "Update" %>

</div>

web/templates/project/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert pa4 br2 mb4 white bg-light-red b--red tc mt3">
      Oops, something went wrong! Please check the errors below.
    </div>
  <% end %>

  <%= component "form_divider.html", title: "Project details" %>
  <%= component "dropdown.html",
  form: f,
  atom: :type,
  label: "Project type",
  options: ["Feature Film": "feature", "Television": "television"],
  prompt: "select..."
  %>

  <%= component "dropdown.html",
  form: f,
  atom: :budget,
  options: ["None/Low": "low", "Mid": "mid", "Big": "big"],
  prompt: "select..."
  %>

  <%= component "input.html",
  form: f,
  atom: :name,
  placeholder: "Project title"
  %>

  <%= component "input.html",
  form: f,
  atom: :codename,
  placeholder: "Project codename"
  %>

  <%= component "input.html",
  form: f,
  atom: :description,
  placeholder: "Brief description of the project"
  %>

  <%= component "date.html",
  form: f,
  atom: :start_date,
  label: "Shoot start date"
  %>

  <%= component "number_input.html",
  form: f,
  atom: :duration,
  placeholder: "",
  label: "Shoot duration (number of weeks)"
  %>

  <%= component "input.html",
  form: f,
  atom: :studio_name,
  placeholder: "",
  label: "Studio/Production company"
  %>

  <%= component "input.html",
  form: f,
  atom: :locations,
  placeholder: "e.g. Paris, London, Shepperton..."
  %>

  <%= component "dropdown.html",
  form: f,
  atom: :holiday_rate,
  options: ["10.77%": 0.1077, "12.07%": 0.1207],
  prompt: "select..."
  %>

  <%= component "textarea.html",
  form: f,
  atom: :additional_notes,
  placeholder: "(max 300 characters)"
  %>

  <%= component "form_divider.html", title: "Company details" %>

  <%= component "input.html",
  form: f,
  atom: :company_name,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :company_address_1,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :company_address_2,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :company_address_city,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :company_address_postcode,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :company_address_country,
  placeholder: ""
  %>

  <%= component "form_divider.html", title: "Operating base details" %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_address_1,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_address_2,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_address_city,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_address_postcode,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_address_country,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_tel,
  placeholder: ""
  %>

  <%= component "input.html",
  form: f,
  atom: :operating_base_email,
  placeholder: ""
  %>

  <%= component "submit_button.html", title: "#{@button_text} Project" %>

<% end %>

web/templates/project/new.html.eex
<div class=" mt6 center">

  <%= link "Dashboard", to: dashboard_path(@conn, :index), class: "link no-underline k-indigo" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
  <div class="ma2 k-light-indigo dib">Create project</div>

  <h1 class="k-indigo top--header absolute fw4 mb0">Create project</h1>

  <%= render "form.html", changeset: @changeset,
                          action: project_path(@conn, :create),
                          button_text: "Create"
                          %>
</div>

web/templates/project/show.html.eex
<%= link "Dashboard", to: dashboard_path(@conn, :index), class: "no-underline k-indigo" %>
<img src="/images/breadcrumb-arrow.svg" class="w1 ml3" />
<%= link "Project", to: project_offer_path(@conn, :index, @project), class: "ma2 k-indigo no-underline" %>
<img src="/images/breadcrumb-arrow.svg" class="w1 ml2" />
<div class="ma2 k-light-indigo dib">Project details</div>

<%= link "Edit project", to: project_path(@conn, :edit, @project), class: "ma1 k-indigo no-underline fr"%>

<h1 class="k-indigo top--header absolute fw4 mb0"><%= @project.codename %></h1>

<ul class="list pl0">
  <%= component "form_divider.html", title: "Project details" %>
  <%= for {atom, label, formatted} <- [
    {:type, nil, format_type(@project.type)},
    {:budget, nil, format_budget(@project.budget)},
    {:codename, nil, nil},
    {:description, nil, nil},
    {:start_date, "Shoot start date", format_date(@project.start_date)},
    {:duration, "Shoot duration", format_duration(@project.duration)},
    {:studio_name, "Studio/Production company", nil},
    {:holiday_rate, nil, format_holiday_rate(@project.holiday_rate)},
    {:locations, nil, nil},
    {:additional_notes, nil, nil}
  ] do %>
    <%= component "data.html",
    data: formatted || Map.get(@project, atom),
    label: label || format_label(atom)
    %>
  <% end %>

  <%= component "form_divider.html", title: "Company details" %>
  <%= for {atom, label} <- [
    {:company_name, nil},
    {:company_address_1, nil},
    {:company_address_2, nil},
    {:company_address_city, nil},
    {:company_address_postcode, nil},
    {:company_address_country, nil}
  ] do %>
    <%= component "data.html",
    data: Map.get(@project, atom),
    label: label || format_label(atom)
    %>
  <% end %>

  <%= component "form_divider.html", title: "Operating base" %>
  <%= for {atom, label} <- [
    {:operating_base_address_1, nil},
    {:operating_base_address_2, nil},
    {:operating_base_address_city, nil},
    {:operating_base_address_postcode, nil},
    {:operating_base_address_country, nil},
    {:operating_base_tel, nil},
    {:operating_base_email, nil}
  ] do %>
    <%= component "data.html",
    data: Map.get(@project, atom),
    label: label || format_label(atom)
    %>
  <% end %>
</ul>

<%= component "form_divider.html", title: "Custom fields" %>
<%= if length(@custom_fields) == 0 do %>
  <div class="tc k-bg-indigo white pa4 f2 br3 mb4">You have not created any custom fields yet</div>
<% end %>
<%= if length(@custom_fields) != 0 do %>
  <div class="mb4">
    <%= for custom_field <- @custom_project_fields do %>
      <%
        value =
          case custom_field.value do
            nil -> "(edit value in offer)"
            value -> value
          end
      %>
      <div class="ba k-b--indigo br3 pa3 pr5 mb2 k-bg-input relative">
        <div class="dib ml3"><%= custom_field.type %></div>
        <div class="dib ml3"><%= String.capitalize(custom_field.name) %>:</div>
        <div class="dib ml3"><%= String.capitalize(value) %></div>

        <%= link to: project_custom_field_path(@conn, :delete, @project, custom_field, add: false),
          method: :delete,
          data: [confirm: "Are you sure?"] do %>
          <img class="absolute k-w2-5 k-top-center right-1" src="/images/delete.svg" />
        <% end %>
      </div>
    <% end %>
    <%= for custom_field <- @custom_offer_fields do %>
      <%
        value =
          case custom_field.value do
            nil -> "(edit value per offer)"
            value -> value
          end
      %>
      <div class="ba k-b--indigo br3 pa3 pr5 mb2 k-bg-input relative">
        <div class="dib ml3" style="padding-right:1.1rem;"><%= custom_field.type %></div>
        <div class="dib ml3"><%= String.capitalize(custom_field.name) %>:</div>
        <div class="dib ml3"><%= String.capitalize(value) %></div>

        <%= link to: project_custom_field_path(@conn, :delete, @project, custom_field, add: false),
          method: :delete,
          data: [confirm: "Are you sure?"] do %>
          <img class="absolute k-w2-5 k-top-center right-1" src="/images/delete.svg" />
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<div class="pa3 ba k-b-indigo br3 w-50-l k-m-auto">
  <%= form_for @custom_field_changeset, project_custom_field_path(@conn, :create, @project), fn f -> %>
    <%= component "dropdown.html",
    form: f,
    atom: :type,
    options: ["Offer", "Project"],
    id: "custom_field_dropdown",
    container_id: "custom_field_dropdown_container"
    %>
    <%= component "input.html",
    form: f,
    atom: :name,
    placeholder: "Shoot day duration"
    %>
    <%= component "input.html",
    form: f,
    atom: :value,
    placeholder: "10 hours",
    container_id: "custom_field_value_container",
    id: "custom_field_value_input",
    class: "dn"
    %>
    <%= component "submit_button.html",
    form: f,
    title: "Add custom field"
    %>
  <% end %>
</div>


<div class="mb4">
  <%= component "form_divider.html", title: "Contracts" %>
  <%= if length(@deals) == 0 do %>
    <div class="tc k-bg-indigo white pa4 f2 br3">You have not uploaded any Contracts yet</div>
  <% end %>
  <div class="tc">
    <%= for deal <- @deals do %>
      <%
        title =
          case length(deal.signees) == 0 do
            true -> "Add"
            false -> "Edit"
          end
        invert = !(length(deal.signees) == 0)
      %>
      <div class="dib tc">
        <div class="relative dib">
          <img class="w5 dib ma1" src="/images/file.png" />
          <%= link to: project_document_path(@conn, :delete, @project, deal),
            method: :delete,
            data: [confirm: "Are you sure?"] do %>
            <img class="absolute k-w2-5 top-0 left-1" src="/images/delete.svg" />
          <% end %>
        </div>
        <div class="tc f5"><%= deal.name %></div>
        <div class="w-50">
          <%= component "button.html", title: "#{title} Approvers", link: project_document_signee_path(@conn, :add, @project, deal), invert: invert %>
        </div>
      </div>
    <% end %>
  </div>
  <%= component "form_divider.html", title: "Forms" %>
  <%= if length(@forms) == 0 do %>
    <div class="tc k-bg-indigo white pa4 f2 br3">You have not uploaded any Forms yet</div>
  <% end %>
  <div class="tc">
    <%= for form <- @forms do %>
    <% title =
        case length(form.signees) == 0 do
          true -> "Add"
          false -> "Edit"
        end
    %>
      <div class="dib tc">
        <div class="relative dib">
          <img class="w5 dib ma1" src="/images/file.png" />
          <%= link to: project_document_path(@conn, :delete, @project, form),
            method: :delete,
            data: [confirm: "Are you sure?"] do %>
            <img class="absolute k-w2-5 top-0 left-1" src="/images/delete.svg" />
          <% end %>
        </div>
        <div class="tc f5"><%= form.name %></div>
        <%= component "button.html", title: "#{title} Approvers", link: project_document_signee_path(@conn, :add, @project, form), class: "w-50" %>
      </div>
    <% end %>
  </div>
  <%= component "form_divider.html", title: "Information" %>
  <%= if length(@info) == 0 do %>
    <div class="tc k-bg-indigo white pa4 f2 br3">You have not uploaded any Information yet</div>
  <% end %>
  <div class="tc">
    <%= for info <- @info do %>
      <div class="dib tc">
        <div class="relative dib">
          <img class="w5 dib ma1" src="/images/file.png" />
          <%= link to: project_document_path(@conn, :delete, @project, info),
            method: :delete,
            data: [confirm: "Are you sure?"] do %>
            <img class="absolute k-w2-5 top-0 left-1" src="/images/delete.svg" />
          <% end %>
        </div>
        <div class="tc f5"><%= info.name %></div>
      </div>
    <% end %>
  </div>
</div>

<div class="w-50-l pa3 ba k-b--indigo k-m-auto br3">
  <div class="tc mb3 f2">Upload a project document</div>
  <%= form_for @document_changeset, project_document_path(@conn, :create, @project), [multipart: true], fn f -> %>
  <div class="mt4">
    <%= component "dropdown.html",
    form: f,
    atom: :category,
    options: [
      "Contracts": "Deal",
      "Forms": "Form",
      "Information": "Info"
      ],
    prompt: "Pick a document category",
    label: "Category",
    id: "category_dropdown"
    %>
    <%= component "dropdown.html",
    form: f,
    atom: :contract_name,
    options: [
      "START FORM",
      "DIRECT HIRE",
      "PAYE",
      "SCHEDULE-D",
      "LOAN OUT",
      "CONSTRUCTION DIRECT HIRE",
      "CONSTRUCTION PAYE",
      "CONSTRUCTION SCHEDULE-D",
      "CONSTRUCTION LOAN OUT",
      "TRANSPORT DIRECT HIRE",
      "TRANSPORT PAYE",
      "TRANSPORT SCHEDULE-D",
      "TRANSPORT LOAN OUT",
      "DAILY DIRECT HIRE",
      "DAILY PAYE",
      "DAILY SCHEDULE-D",
      "DAILY LOAN OUT",
      "DAILY CONSTRUCTION DIRECT HIRE",
      "DAILY CONSTRUCTION PAYE",
      "DAILY CONSTRUCTION SCHEDULE-D",
      "DAILY CONSTRUCTION LOAN OUT",
      "DAILY TRANSPORT DIRECT HIRE",
      "DAILY TRANSPORT PAYE",
      "DAILY TRANSPORT SCHEDULE-D",
      "DAILY TRANSPORT LOAN OUT",
      "BOX RENTAL FORM",
      "EQUIPMENT RENTAL FORM",
      "VEHICLE ALLOWANCE"
      ],
    prompt: "Pick a contract type",
    label: "Contract",
    id: "contract_dropdown",
    container_id: "contract_dropdown_container",
    class: "dn"
    %>
    <%= component "input.html",
    form: f,
    atom: :name,
    placeholder: "Enter the document name",
    label: "Name",
    id: "non_contract_dropdown",
    container_id: "non_contract_dropdown_container",
    class: "dn"
    %>
  </div>
    <%= component "file_upload.html",
    form: f,
    atom: :file,
    file_types: "pdf",
    conn: @conn
    %>
    <%= component "submit_button.html", title: "Upload" %>
  <% end %>
</div>
<%= component "form_divider.html", title: "Approvers" %>
<%= if length(@signees) == 0 do %>
  <div class="tc k-bg-indigo white pa4 f2 br3 mb4">
    Add approvers to this project
  </div>
<% end %>
<%= if length(@signees) != 0 do %>
  <div class="mb4">
    <%= for signee <- @signees do %>
      <div class="ba k-b--indigo br3 pa3 pr5 mb2 k-bg-input relative">
        <div class="dib ml3"><%= signee.name %></div>
        <div class="dib ml3"><%= signee.role %></div>
        <div class="dib ml3"><%= signee.email %></div>
        <div class="dib ml3">(<%= signee.approver_type %>)</div>

        <%= link to: project_signee_path(@conn, :delete, @project, signee),
          method: :delete,
          data: [confirm: "Are you sure?"] do %>
          <img class="absolute k-w2-5 k-top-center right-1" src="/images/delete.svg" />
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<div class="pa3 ba k-b-indigo br3 w-50-l k-m-auto">
  <%= form_for @signee_changeset, project_signee_path(@conn, :create, @project), fn f -> %>
    <%= component "input.html",
    form: f,
    atom: :name,
    placeholder: "John Smith"
    %>
    <%= component "input.html",
    form: f,
    atom: :email,
    placeholder: "johnsmith@gmail.com"
    %>
    <%= component "input.html",
    form: f,
    atom: :role,
    placeholder: "Producer"
    %>
    <%= component "dropdown.html",
    form: f,
    atom: :approver_type,
    options: ["Approver", "Recipient"],
    prompt: "select..."
    %>
    <%= component "submit_button.html",
    form: f,
    title: "Add approver"
    %>
  <% end %>
</div>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script>require("web/static/js/app").App.document_upload_listeners()</script>
<script>require("web/static/js/app").App.custom_field_listeners()</script>