web/router.ex
defmodule Engine.Router do
  use Engine.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Engine.Auth, repo: Engine.Repo
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  scope "/", Engine do
    pipe_through :browser # Use the default browser stack
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/terms", InfoController, :terms
    get "/privacy", InfoController, :privacy
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    resources "/password", PasswordController, only: [:new, :create, :edit, :update]
    get "/", DashboardController, :index
  end

  # authed routes
  scope "/", Engine do
    pipe_through [:browser, :authenticate]
    # get "/admin-dashboard", AdminDashboardController, :index
    post "/startpack/:id", StartpackController, :update
    post "/startpack/:id/delete-file", StartpackController, :delete_uploaded_files
    resources "/startpack", StartpackController, except: [:new, :create, :delete]
    # post "/projects/:project_id/offers/:offer_id/send_offer", OfferController, :send_offer
    resources "/projects", ProjectController do
      resources "/custom_fields", CustomFieldController, only: [:create, :delete]
      resources "/documents", DocumentController do
        get "/signees/new", SigneeController, :add
        post "/signees/new", SigneeController, :add_signee
        delete "/signees", SigneeController, :clear_signees
      end
      resources "/signees", SigneeController, only: [:create, :delete]
      post "/offers/:offer_id/send_offer", OfferController, :send_offer
      resources "/offers", OfferController do
        # project_offer_altered_document_path(conn, project, offer)
        # /projects/:project_id/offers/:offer_id/altered_documents/sign

        get "/custom_fields/add", CustomFieldController, :add
        post "/custom_fields/:id/save", CustomFieldController, :save
        post "/custom_fields/:id/revise", CustomFieldController, :revise
        get "/altered_documents/sign", AlteredDocumentController, :sign
      end
      put "/offers/:id/response", OfferController, :response
    end
  end

  # admin authed routes
  scope "/admin", Engine do
    pipe_through [:browser, :authenticate_admin]
    get "/dashboard", AdminDashboardController, :index
    get "/custom-fields", AdminDashboardController, :custom_fields
    get "/users", AdminDashboardController, :users
  end

  # Other scopes may use custom stacks.
  # scope "/api", Engine do
  #   pipe_through :api
  # end
end

web/controllers/startpack_controller.ex
defmodule Engine.StartpackController do
  use Engine.Web, :controller

  alias Engine.{Startpack, Offer, Controllers.Helpers}
  # possible solution for multiple fields
   @file_upload_keys [
     {"passport_image", "passport_url"},
     {"vehicle_insurance_image", "vehicle_insurance_url"},
     {"vehicle_license_image", "vehicle_license_url"},
     {"box_rental_image", "box_rental_url"},
     {"equipment_rental_image", "equipment_rental_url"},
     {"p45_image", "p45_url"},
     {"schedule_d_letter_image", "schedule_d_letter_url"},
     {"loan_out_company_cert_image", "loan_out_company_cert_url"}
   ]

  def index(conn, _params, user) do
    startpack = Repo.one(Helpers.user_startpack(user))
    startpack_map = Map.from_struct(startpack)
    uploaded_files = get_uploaded_files(startpack_map)
    changeset = Startpack.changeset(%Startpack{}, startpack_map)
    delete_changeset = Startpack.delete_changeset(%Startpack{}, startpack_map)
    case Map.has_key?(conn.query_params, "offer_id") do
      true ->
        offer_id = String.to_integer(conn.query_params["offer_id"])
        case Repo.get_by(Offer, id: offer_id) do
          nil ->
            render(conn, "index.html", startpack: startpack, changeset: changeset, offer: %{}, user: user, delete_changeset: delete_changeset, uploaded_files: uploaded_files)
          offer ->
            mother_changeset = Startpack.mother_changeset(%Startpack{}, Map.from_struct(startpack), offer)
            mother_changeset = %{mother_changeset | action: :insert}
            render(conn, "index.html", startpack: startpack, changeset: mother_changeset, offer: offer, user: user, delete_changeset: delete_changeset, uploaded_files: uploaded_files)
        end
      false ->
        render(conn, "index.html", startpack: startpack, changeset: changeset, offer: %{}, user: user, delete_changeset: delete_changeset, uploaded_files: uploaded_files)
      end
  end

  def update(conn, %{"id" => id, "startpack" => startpack_params}, user) do
    %{
      "loan_out_company_address" => loca,
      "student_loan_not_repayed?" => student_loan_not_repayed?
    } = startpack_params

    startpack_params = remove_student_loan_values_if_repaid(startpack_params, student_loan_not_repayed?)

    single_line_address = Regex.replace(~r/\r\n/, loca, " ")
    startpack_params =
      startpack_params
      |> Map.delete("loan_out_company_address")
      |> Map.put_new("loan_out_company_address", single_line_address)
    startpack = Repo.get!(Startpack, id)
    startpack_map = Map.from_struct(startpack)

    uploaded_files = get_uploaded_files(startpack_map)
    delete_changeset = Startpack.delete_changeset(%Startpack{}, startpack_map)
    image_changeset = Startpack.upload_type_validation(%Startpack{}, startpack_params)
    offer_id = Map.get(conn.query_params, "offer_id", "")
    case image_changeset.valid? do
      false ->
        conn
        |> put_flash(:error, "Error updating startpack")
        |> render("index.html", changeset: image_changeset, startpack: startpack, offer: %{}, user: user, delete_changeset: delete_changeset, uploaded_files: uploaded_files)
      true ->
        urls = Engine.S3.upload_many(startpack_params, @file_upload_keys, "#{String.upcase(user.first_name)}_#{String.upcase(user.last_name)}")

        params = Map.merge(startpack_params, urls)

        changeset = Startpack.changeset(startpack, params)

        _startpack = Repo.update!(changeset)
        case offer_id == "" do
          true ->
            conn
            |> put_flash(:info, "Startpack updated successfully")
            |> redirect(to: startpack_path(conn, :index))
          false ->
            conn
            |> put_flash(:info, "Startpack updated successfully")
            |> redirect(to: startpack_path(conn, :index, offer_id: offer_id))
      end
    end
  end

  defp remove_student_loan_values_if_repaid(startpack_params, not_repaid?) do
    case not_repaid? == true || not_repaid? == "true" do
      false ->
        startpack_params
        |> Map.delete("student_loan_repay_direct?")
        |> Map.put_new("student_loan_repay_direct?", nil)
        |> Map.delete("student_loan_plan_1?")
        |> Map.put_new("student_loan_plan_1?", nil)
        |> Map.delete("student_loan_finished_before_6_april?")
        |> Map.put_new("student_loan_finished_before_6_april?", nil)
      true ->
        startpack_params
    end
  end

  def delete_uploaded_files(conn, %{"id" => startpack_id, "startpack" => startpack_params}, _user) do
    startpack = Repo.get(Startpack, startpack_id)
    changeset = Startpack.delete_changeset(startpack, startpack_params)
    Repo.update!(changeset)
    conn
    |> put_flash(:info, "File deleted successfully")
    |> redirect(to: startpack_path(conn, :index))
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
          [conn, conn.params, conn.assigns.current_user])
  end

  defp convert_atom_to_name(atom) do
    atom
    |> Atom.to_string()
    |> String.replace("_url", "")
    |> String.replace("_", " ")
    |> String.replace("license", "licence")
    |> String.upcase()
  end

  defp get_uploaded_files(startpack_map) do
    upload_map = Map.take(startpack_map, [
      :loan_out_company_cert_url,
      :schedule_d_letter_url,
      :p45_url,
      :equipment_rental_url,
      :box_rental_url,
      :vehicle_license_url,
      :vehicle_insurance_url,
      :passport_url
      ])
    upload_atoms = Map.keys(upload_map)
    upload_values = Map.values(upload_map)
    upload_names = Enum.map(upload_atoms, fn atom -> convert_atom_to_name(atom) end)
    atom_keyword_list = for atom <- upload_atoms do
      %{atom: atom}
    end
    value_keyword_list = for value <- upload_values do
      %{value: value}
    end
    name_keyword_list = for name <- upload_names do
      %{name: name}
    end
    zipped_list = Enum.zip([name_keyword_list, atom_keyword_list, value_keyword_list])
    Enum.map(zipped_list, fn {name_map, atom_map, value_map} -> %{name: name_map.name, atom: atom_map.atom, value: value_map.value} end)
    |> Enum.filter(fn map -> map.value != nil end)
    |> Enum.filter(fn map -> map.value != "" end)
  end
end

web/views/startpack_view.ex
defmodule Engine.StartpackView do
  use Engine.Web, :view

  def for_paye_only do
    ["This is my first job since last 6th April, I have not been receiving taxable jobseekers allowance, employment and support allowance, taxable incapacity benefit, state or occupational pension.": "first since april",
     "This is now my only job, but since last 6 April I have had another job, or have received taxable Jobseeker's Allowance, Employment and Support Allowance or Incapacity Benefit. I do not receive a state or occupational pension.": "now only job",
     "I have another job or receive a state or occupational pension": "have another job"
    ]
  end
end

web/templates/startpack/form.html.eex
<div class="pt4">
  <%= if length(@uploaded_files) != 0 do %>
    <%= component "form_divider.html", title: "Uploaded files" %>
    <div class="tc">
      <%= for file <- @uploaded_files do %>
        <div class="dib mb4">
          <%= form_for @delete_changeset, startpack_path(@conn, :delete_uploaded_files, @startpack), fn f -> %>
            <div class="dib relative">
              <img class="w5" src="/images/file.png"  />
              <div class="f5 tc"><%= String.replace(file.name, "RENTAL", "INVENTORY") %></div>
              <%= hidden_input f, file.atom, value: nil %>
              <%= submit "x", class: "k-bg-error k-light-indigo br-100 bn absolute k-top--0-5 left-0 pl3 pr3 f2 nunito tc outline-0 pointer" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div>
  <%= component "form_divider.html", title: "Profile info" %>
  <%= component "information.html",
  data: @user.email,
  label: "Email address"
  %>
  <%= component "information.html",
  data: @user.first_name,
  label: "First name"
  %>

  <%= component "information.html",
  data: @user.last_name,
  label: "Last name"
  %>
  <br/>
  <%= component "button.html", link: user_path(@conn, :edit, @user), title: "Edit profile info" %>
</div>
<div>
  <%= form_for @changeset, @action, [multipart: true], fn f -> %>

    <div class="pt5-ns pt4">
    <%= component "form_divider.html", title: "Basic info" %>
    <%= component "dropdown.html",
    form: f,
    atom: :gender,
    options: ["Male", "Female", "Other", "Prefer not to say"],
    prompt: "select..."
    %>

    <%= component "input.html",
    form: f,
    atom: :middle_names,
    label: "Middle name(s)"
    %>

    <%= component "input.html",
    form: f,
    atom: :aka,
    label: "Also known as"
    %>

    <%= component "input.html",
    form: f,
    atom: :screen_credit_name
    %>

    <%= component "input.html",
    form: f,
    atom: :mobile_tel
    %>

    <%= component "input.html",
    form: f,
    atom: :emergency_contact_name
    %>

    <%= component "input.html",
    form: f,
    atom: :emergency_contact_relationship
    %>

    <%= component "input.html",
    form: f,
    atom: :emergency_contact_tel
    %>

    <%= component "form_divider.html", title: "Personal info" %>

    <%= component "date.html",
    form: f,
    atom: :date_of_birth,
    year_from: 1930,
    year_to: Date.utc_today().year
    %>

    <%= component "input.html",
    form: f,
    atom: :place_of_birth
    %>

    <%= component "input.html",
    form: f,
    atom: :country_of_legal_nationality
    %>


    <%= component "input.html",
    form: f,
    atom: :country_of_permanent_residence
    %>

    <%= component "input.html",
    form: f,
    atom: :passport_full_name,
    placeholder: "Your full name as it appears on your passport (inc. middle name(s))"
    %>

    <%= component "input.html",
    form: f,
    atom: :passport_number
    %>


    <%= component "date.html",
    form: f,
    atom: :passport_expiry_date,
    year_to: Date.utc_today().year + 50
    %>

    <%= component "input.html",
    form: f,
    atom: :passport_issuing_country
    %>

    <%= component "file_upload.html",
    form: f,
    atom: :passport_image,
    url_atom: :passport_url,
    helper_text: "Upload a file of your passport",
    file_types: "pdf, jpg, png",
    image_url: @startpack.passport_url,
    hide_label: true,
    conn: @conn
    %>


    <%= component "form_divider.html", title: "Contact info" %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_1
    %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_2
    %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_city
    %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_postcode
    %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_country
    %>

    <%= component "input.html",
    form: f,
    atom: :primary_address_tel
    %>

    <%= component "form_divider.html", title: "Deal info" %>

    <div conditional class="mb5">
      <%= label f, "Check the box if your deal will be done through your agent", class: "dib mw-100 mb2 fw4 k-inline-checkbox-label" %>
      <%= checkbox f, :agent_deal?, class: "db mr2 k-w1-5 h2" %>
      <%= error_tag f, :agent_deal? %>

      <div conditional_child class="mt4">
        <%= component "input.html",
        form: f,
        atom: :agent_name
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_company
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_address
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_tel
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_email_address
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_name
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_address
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_sort_code
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_account_number
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_account_name
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_account_swift_code,
        label: "Agent bank account SWIFT code"
        %>

        <%= component "input.html",
        form: f,
        atom: :agent_bank_account_iban,
        label: "Agent bank account IBAN"
        %>
      </div>
    </div>

    <%= component "form_divider.html", title: "Allowances" %>

    <%= component "number_input.html",
    form: f,
    atom: :box_rental_value,
    label: "Box rental inventory value",
    placeholder: "Enter a number"
    %>

    <%= component "file_upload.html",
    form: f,
    atom: :box_rental_image,
    url_atom: :box_rental_url,
    helper_text: "Upload your box inventory list with insurance values",
    file_types: "pdf, jpg, png",
    image_url: @startpack.box_rental_url,
    hide_label: true,
    conn: @conn
    %>

    <%= component "number_input.html",
    form: f,
    atom: :equipment_rental_value,
    label: "Equipment rental inventory value",
    placeholder: "Enter a number"
    %>

    <%= component "file_upload.html",
    form: f,
    atom: :equipment_rental_image,
    url_atom: :equipment_rental_url,
    helper_text: "Upload your equipment inventory list with insurance values",
    file_types: "pdf, jpg, png",
    image_url: @startpack.equipment_rental_url,
    hide_label: true,
    conn: @conn
    %>

    <div class="mb3 f3">Your vehicle details for site access and parking:</div>
    <%= component "checkbox.html",
    form: f,
    atom: :vehicle_bring_own?,
    label: "Check the box if you bring your own vehicle"
    %>

    <br />
    <%= component "input.html",
    form: f,
    atom: :vehicle_make
    %>

    <%= component "input.html",
    form: f,
    atom: :vehicle_model
    %>

    <%= component "input.html",
    form: f,
    atom: :vehicle_colour
    %>

    <%= component "input.html",
    form: f,
    atom: :vehicle_registration
    %>

    <%= component "file_upload.html",
    form: f,
    atom: :vehicle_insurance_image,
    url_atom: :vehicle_insurance_url,
    helper_text: "Upload a file of proof of vehicle insurance for business use",
    file_types: "pdf, jpg, png",
    image_url: @startpack.vehicle_insurance_url,
    hide_label: true,
    conn: @conn
    %>

    <%= component "file_upload.html",
    form: f,
    atom: :vehicle_license_image,
    url_atom: :vehicle_license_url,
    helper_text: "Upload a file of your driving licence",
    file_types: "pdf, jpg, png",
    image_url: @startpack.vehicle_license_url,
    hide_label: true,
    conn: @conn
    %>

    <%= component "form_divider.html", title: "Payment info" %>

    <%= component "input.html",
    form: f,
    atom: :national_insurance_number
    %>


    <%= component "file_upload.html",
    form: f,
    atom: :p45_image,
    url_atom: :p45_url,
    helper_text: "Upload a file of your P45",
    file_types: "pdf, jpg, png",
    image_url: @startpack.p45_url,
    hide_label: true,
    conn: @conn
    %>

    <%= component "radio.html",
    form: f,
    atom: :for_paye_only,
    label: "For PAYE contracts only (select one)",
    radios: Engine.StartpackView.for_paye_only()
    %>

    </br>



    <%= component "form_divider.html", title: "", colour: "k-b--grey" %>

    <div conditional class="mb5">
      <%= label f, :student_loan_not_repayed?, "Check the box if you have a student loan which is not fully repaid", class: "dib mw-100 mb2 fw4 k-inline-checkbox-label" %>
      <%= checkbox f, :student_loan_not_repayed?, class: "db mr2 k-w1-5 h2" %>
      <%= error_tag f, :student_loan_not_repayed? %>

      <div conditional_child class="mt4">

        <%= component "radio.html",
        form: f,
        atom: :student_loan_repay_direct?,
        radios: ["Yes": true, "No": false],
        label: "You are repaying your Loan direct to the Student Loan Co."
        %>

        <%= component "radio.html",
        form: f,
        atom: :student_loan_plan_1?,
        radios: ["Student loan Plan 1": true, "Student loan Plan 2": false],
        label: "Which student loan plan do you have?"
        %>

        <%= component "radio.html",
        form: f,
        atom: :student_loan_finished_before_6_april?,
        radios: ["Yes": true, "No": false],
        label: "You finished your studies before last April 6th."
        %>

      </div>
    </div>

    <%= component "form_divider.html", title: "", colour: "k-b--grey" %>

    <%= component "file_upload.html",
    form: f,
    atom: :schedule_d_letter_image,
    label: "Schedule D letter file",
    url_atom: :schedule_d_letter_url,
    helper_text: "Upload a file of your Schedule D letter",
    file_types: "pdf, jpg, png",
    image_url: @startpack.schedule_d_letter_url,
    hide_label: true,
    conn: @conn
    %>


    <%= component "input.html",
    form: f,
    atom: :vat_number,
    label: "VAT number"
    %>

    <%= component "form_divider.html", title: "", colour: "k-b--grey" %>


    <div conditional class="mb5">
      <div class="dib mw-100 mb2 fw4 k-inline-checkbox-label k-inline-checkbox-label">Check this box to provide your <strong>loan out company</strong> details</div>
      <%= checkbox f, :use_loan_out_company?, class: "db mr2 k-w1-5 h2" %>
      <%= error_tag f, :use_loan_out_company? %>

      <div conditional_child class="mt4">

        <%= component "input.html",
        form: f,
        atom: :loan_out_company_name
        %>

        <%= component "input.html",
        form: f,
        atom: :loan_out_company_registration_number
        %>

        <%= component "input.html",
        form: f,
        atom: :loan_out_company_address,
        placeholder: "(max 300 characters)"
        %>


        <%= component "input.html",
        form: f,
        atom: :loan_out_company_email
        %>

        <%= component "file_upload.html",
        form: f,
        atom: :loan_out_company_cert_image,
        url_atom: :loan_out_company_cert_url,
        helper_text: "Upload a file of your loan out company certificate",
        file_types: "pdf, jpg, png",
        image_url: @startpack.loan_out_company_cert_url,
        hide_label: true,
        conn: @conn
        %>
      </div>
    </div>

    <%= component "form_divider.html", title: "", colour: "k-b--grey" %>

    <%= component "input.html",
    form: f,
    atom: :bank_name
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_address
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_account_users_full_name,
    label: "Full name on bank account"
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_account_number
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_sort_code
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_iban,
    label: "Bank IBAN"
    %>

    <%= component "input.html",
    form: f,
    atom: :bank_swift_code,
    label: "Bank SWIFT code"
    %>
    </div>

    <%= component "submit_button.html", title: "Update Startpack" %>
  <% end %>
</div>



<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script>require("web/static/js/app").App.studentLoanRadios()</script>

web/templates/startpack/index.html.eex
<div class=" mt6 center">


  <h1 class="k-indigo top--header absolute fw4 mb0">Edit startpack</h1>
  <%= link "Dashboard", to: dashboard_path(@conn, :index), class: "no-underline k-indigo" %>
  <img src="/images/breadcrumb-arrow.svg" class="w1 ml3" />
  <div class="ma2 k-light-indigo dib mb4">Startpack</div>

  <%= if length(@changeset.errors) != 0 do %>
  <div class="alert alert-danger tc br3 pa4 ma2 mb3 f2 mt3">
    <div>Fill the boxes below required for this offer</div>
  </div>
  <% end %>
  <%= if Map.has_key?(@offer, :project_id) && Map.has_key?(@offer, :id) do %>
  <div>
    <%= component "button.html", title: "Back to offer", link: project_offer_path(@conn, :show, @offer.project_id, @offer.id) %>
  </div>
  <% end %>
  <% offer_id = case Map.has_key?(@conn.query_params, "offer_id") do
      true ->
        %{"offer_id" => offer_id} = @conn.query_params
        offer_id
      false -> nil
    end %>

  <%= render "form.html", changeset: @changeset,
                          action: startpack_path(@conn, :update, @startpack, offer_id: offer_id),
                          offer: @offer,
                          startpack: @startpack,
                          conn: @conn,
                          user: @user,
                          uploaded_files: @uploaded_files,
                          delete_changeset: @delete_changeset,
                          offer_id: offer_id %>
</div>